[package]
name = "reflex-search"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reflex-types.workspace = true
reflex-canonical.workspace = true
reflex-domain.workspace = true
smallvec.workspace = true
bytes.workspace = true
rand.workspace = true
rand_chacha.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[lints]
workspace = true
