[package]
name = "reflex-analytics"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reflex-types.workspace = true
reflex-canonical.workspace = true
reflex-dataset.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
