[package]
name = "reflex-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reflex-cas.workspace = true
reflex-types.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
