[package]
name = "reflex-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "reflex-worker"
path = "src/main.rs"

[dependencies]
reflex-types.workspace = true
reflex-cas.workspace = true
reflex-ledger.workspace = true
reflex-meta.workspace = true
reflex-meta-sqlite.workspace = true
reflex-runtime.workspace = true
reflex-bench.workspace = true
reflex-search.workspace = true
reflex-domain.workspace = true
reflex-domain-bitvec.workspace = true
reflex-scheduler.workspace = true
bytes.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
