[package]
name = "reflex-bitvec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rayon = "1.12.0"
reflex = { path = "../reflex" }

[lints]
workspace = true

[dev-dependencies]
reflex = { path = "../reflex", features = ["internal-experiments"] }
reflex-bundle = { path = "../reflex-bundle" }
sha2 = { version = "0.11", default-features = false }
