[package]
name = "reflex-analytics-bin"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "reflex-analytics"
path = "src/main.rs"

[dependencies]
reflex-types.workspace = true
reflex-analytics.workspace = true
clap.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[lints]
workspace = true
